// Team color themes — primary (CTAs/links) + secondary (subtle accents/borders)
// Background stays fixed (dark stadium-night); these only shift accent colors.
export const teamThemes = {
  ARI: { name: 'Arizona Diamondbacks', primary: '#A71930', secondary: '#E3D4AD' },
  ATL: { name: 'Atlanta Braves',       primary: '#CE1141', secondary: '#13274F' },
  BAL: { name: 'Baltimore Orioles',    primary: '#DF4601', secondary: '#000000' },
  BOS: { name: 'Boston Red Sox',       primary: '#BD3039', secondary: '#0C2340' },
  CHC: { name: 'Chicago Cubs',         primary: '#0E3386', secondary: '#CC3433' },
  CWS: { name: 'Chicago White Sox',    primary: '#C4CED4', secondary: '#27251F' },
  CIN: { name: 'Cincinnati Reds',      primary: '#C6011F', secondary: '#000000' },
  CLE: { name: 'Cleveland Guardians',  primary: '#E31937', secondary: '#0C2340' },
  COL: { name: 'Colorado Rockies',     primary: '#33006F', secondary: '#C4CED4' },
  DET: { name: 'Detroit Tigers',       primary: '#FA4616', secondary: '#0C2340' },
  HOU: { name: 'Houston Astros',       primary: '#EB6E1F', secondary: '#002D62' },
  KC:  { name: 'Kansas City Royals',   primary: '#004687', secondary: '#BD9B60' },
  LAA: { name: 'Los Angeles Angels',   primary: '#BA0021', secondary: '#003263' },
  LAD: { name: 'Los Angeles Dodgers',  primary: '#005A9C', secondary: '#A5ACAF' },
  MIA: { name: 'Miami Marlins',        primary: '#00A3E0', secondary: '#EF3340' },
  MIL: { name: 'Milwaukee Brewers',    primary: '#FFC52F', secondary: '#12284B' },
  MIN: { name: 'Minnesota Twins',      primary: '#002B5C', secondary: '#D31145' },
  NYM: { name: 'New York Mets',        primary: '#FF5910', secondary: '#002D72' },
  NYY: { name: 'New York Yankees',     primary: '#C4CED3', secondary: '#0C2340' },
  OAK: { name: 'Athletics',            primary: '#EFB21E', secondary: '#003831' },
  PHI: { name: 'Philadelphia Phillies',primary: '#E81828', secondary: '#002D72' },
  PIT: { name: 'Pittsburgh Pirates',   primary: '#FDB827', secondary: '#27251F' },
  SD:  { name: 'San Diego Padres',     primary: '#FFC425', secondary: '#2F241D' },
  SF:  { name: 'San Francisco Giants', primary: '#FD5A1E', secondary: '#27251F' },
  SEA: { name: 'Seattle Mariners',     primary: '#0C2C56', secondary: '#005C5C' },
  STL: { name: 'St. Louis Cardinals',  primary: '#C41E3A', secondary: '#0C2340' },
  TB:  { name: 'Tampa Bay Rays',       primary: '#8FBCE6', secondary: '#092C5C' },
  TEX: { name: 'Texas Rangers',        primary: '#C0111F', secondary: '#003278' },
  TOR: { name: 'Toronto Blue Jays',    primary: '#134A8E', secondary: '#1D2D5C' },
  WSH: { name: 'Washington Nationals', primary: '#AB0003', secondary: '#14225A' },
};