FROM node:20-alpine AS build

WORKDIR /app

COPY package.json ./
COPY client/package.json ./client/
COPY shared/package.json ./shared/

RUN npm install

COPY client/ ./client/
COPY shared/ ./shared/

WORKDIR /app/client

RUN npm run build

FROM caddy:2

COPY --from=build /app/client/dist /srv/client
COPY Caddyfile /etc/caddy/Caddyfile